name: fantastic_weights
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - numpy
  - matplotlib
  - pip
  - pip:
    - wandb

